<?php
namespace App\Services;use App\Core\Database;use PDO;use RuntimeException;
class FormulaAdminService
{
 public function create(array $d,int $env,int $by):int{return Database::transaction(function(PDO $db)use($d,$env,$by){$code=strtoupper(trim((string)($d['codigo']??'')));$name=trim((string)($d['nombre']??''));if(!$code||!$name)throw new RuntimeException('Código y nombre son obligatorios.');$cat=(int)($d['categoria_formula_id']??0);if(!$cat)throw new RuntimeException('Selecciona categoría.');$s=$db->prepare('INSERT INTO formulas(categoria_formula_id,codigo,nombre,descripcion,unidad_resultado_id,creada_por,activo) VALUES(:c,:co,:n,:d,:u,:by,1)');$s->execute(['c'=>$cat,'co'=>$code,'n'=>$name,'d'=>trim((string)($d['descripcion']??''))?:null,'u'=>!empty($d['unidad_resultado_id'])?(int)$d['unidad_resultado_id']:null,'by'=>$by]);$id=(int)$db->lastInsertId();$db->prepare('INSERT INTO formula_entornos(formula_id,entorno_id) VALUES(:f,:e)')->execute(['f'=>$id,'e'=>$env]);$this->newVersion($db,$id,$d,$by);if(!empty($d['especie_ids'])&&is_array($d['especie_ids']))foreach($d['especie_ids'] as $es)$db->prepare('INSERT IGNORE INTO formula_especies(formula_id,especie_id) VALUES(:f,:e)')->execute(['f'=>$id,'e'=>(int)$es]);(new AuditService())->log($by,$env,'FORMULAS','CREAR','formulas',$id);return$id;});}
 public function addVersion(int $formula,array $d,int $env,int $by):int{return Database::transaction(function(PDO $db)use($formula,$d,$env,$by){$s=$db->prepare('SELECT 1 FROM formula_entornos WHERE formula_id=:f AND entorno_id=:e');$s->execute(['f'=>$formula,'e'=>$env]);if(!$s->fetchColumn())throw new RuntimeException('Fórmula no disponible en este entorno.');$id=$this->newVersion($db,$formula,$d,$by);(new AuditService())->log($by,$env,'FORMULAS','NUEVA_VERSION','formula_versiones',$id);return$id;});}
 public function publish(int $version,int $env,int $by):void{Database::transaction(function(PDO $db)use($version,$env,$by){$pub=(int)$db->query("SELECT id FROM estados_formula_version WHERE codigo='PUBLICADA'")->fetchColumn();$s=$db->prepare('SELECT fv.formula_id FROM formula_versiones fv JOIN formula_entornos fe ON fe.formula_id=fv.formula_id WHERE fv.id=:v AND fe.entorno_id=:e');$s->execute(['v'=>$version,'e'=>$env]);$formula=$s->fetchColumn();if(!$formula)throw new RuntimeException('Versión no válida.');$db->prepare('UPDATE formula_versiones SET estado_id=:s,publicada_por=:u,publicada_at=NOW() WHERE id=:v')->execute(['s'=>$pub,'u'=>$by,'v'=>$version]);(new AuditService())->log($by,$env,'FORMULAS','PUBLICAR','formula_versiones',$version);});}
 private function newVersion(PDO $db,int $formula,array $d,int $by):int{$expr=trim((string)($d['expresion']??''));if($expr==='')throw new RuntimeException('La expresión es obligatoria.');$draft=(int)$db->query("SELECT id FROM estados_formula_version WHERE codigo='BORRADOR'")->fetchColumn();$s=$db->prepare('SELECT COALESCE(MAX(numero_version),0)+1 FROM formula_versiones WHERE formula_id=:f');$s->execute(['f'=>$formula]);$n=(int)$s->fetchColumn();$db->prepare('INSERT INTO formula_versiones(formula_id,numero_version,expresion,notas_version,estado_id,creada_por) VALUES(:f,:n,:e,:no,:s,:u)')->execute(['f'=>$formula,'n'=>$n,'e'=>$expr,'no'=>trim((string)($d['notas_version']??''))?:null,'s'=>$draft,'u'=>$by]);$vid=(int)$db->lastInsertId();$vars=$d['variables']??[];if(is_array($vars))foreach($vars as $v){if(empty($v['codigo'])||empty($v['etiqueta']))continue;$db->prepare('INSERT INTO formula_variables(formula_version_id,tipo_variable_id,origen_variable_id,unidad_medida_id,codigo,etiqueta,descripcion,obligatorio,valor_minimo,valor_maximo,valor_default,orden) VALUES(:fv,:t,:o,:u,:c,:e,:d,:ob,:min,:max,:def,:ord)')->execute(['fv'=>$vid,'t'=>(int)($v['tipo_variable_id']??1),'o'=>(int)($v['origen_variable_id']??1),'u'=>!empty($v['unidad_medida_id'])?(int)$v['unidad_medida_id']:null,'c'=>strtoupper(trim($v['codigo'])),'e'=>trim($v['etiqueta']),'d'=>trim((string)($v['descripcion']??''))?:null,'ob'=>!empty($v['obligatorio'])?1:0,'min'=>($v['valor_minimo']??'')!==''?(float)$v['valor_minimo']:null,'max'=>($v['valor_maximo']??'')!==''?(float)$v['valor_maximo']:null,'def'=>($v['valor_default']??'')!==''?(float)$v['valor_default']:null,'ord'=>(int)($v['orden']??0)]);}return$vid;}
}
