<?php
namespace App\Services;
use App\Core\Database;use PDO;use RuntimeException;
class OwnerService
{
 public function create(array $d,int $env,int $by):array{return Database::transaction(function(PDO $db)use($d,$env,$by){$names=trim((string)($d['nombres']??''));if($names==='')throw new RuntimeException('Los nombres son obligatorios.');$email=trim((string)($d['email']??''))?:null;$userId=null;$temp=null;
  if(!empty($d['crear_acceso'])&&$email){$s=$db->prepare('SELECT id FROM usuarios WHERE email=:e AND deleted_at IS NULL LIMIT 1');$s->execute(['e'=>$email]);$userId=$s->fetchColumn()?:null;if(!$userId){$temp=(string)($d['password_temporal']??'');if(strlen($temp)<8)$temp='Vet#'.bin2hex(random_bytes(4));$s=$db->prepare('INSERT INTO usuarios(nombres,apellidos,email,telefono,password_hash,requiere_cambio_password,activo) VALUES(:n,:a,:e,:t,:h,1,1)');$s->execute(['n'=>$names,'a'=>trim((string)($d['apellidos']??'')),'e'=>$email,'t'=>$d['celular']??$d['telefono']??null,'h'=>password_hash($temp,PASSWORD_DEFAULT)]);$userId=(int)$db->lastInsertId();}
   $role=(int)$db->query("SELECT id FROM roles WHERE codigo='CLIENTE' LIMIT 1")->fetchColumn();$s=$db->prepare('INSERT IGNORE INTO usuarios_entornos(usuario_id,entorno_id,activo) VALUES(:u,:e,1)');$s->execute(['u'=>$userId,'e'=>$env]);$s=$db->prepare('INSERT IGNORE INTO usuarios_entornos_roles(usuario_id,entorno_id,rol_id) VALUES(:u,:e,:r)');$s->execute(['u'=>$userId,'e'=>$env,'r'=>$role]);}
  $s=$db->prepare('INSERT INTO propietarios(usuario_id,tipo_identificacion_id,identificacion,nombres,apellidos,email,telefono,celular,direccion,activo) VALUES(:u,:ti,:i,:n,:a,:e,:t,:c,:d,1)');$s->execute(['u'=>$userId,'ti'=>!empty($d['tipo_identificacion_id'])?(int)$d['tipo_identificacion_id']:null,'i'=>trim((string)($d['identificacion']??''))?:null,'n'=>$names,'a'=>trim((string)($d['apellidos']??''))?:null,'e'=>$email,'t'=>trim((string)($d['telefono']??''))?:null,'c'=>trim((string)($d['celular']??''))?:null,'d'=>trim((string)($d['direccion']??''))?:null]);$id=(int)$db->lastInsertId();$s=$db->prepare('INSERT INTO propietarios_entornos(propietario_id,entorno_id,activo) VALUES(:p,:e,1)');$s->execute(['p'=>$id,'e'=>$env]);(new AuditService())->log($by,$env,'PROPIETARIOS','CREAR','propietarios',$id,null,['usuario_id'=>$userId]);return ['id'=>$id,'temporary_password'=>$temp];});}
 public function update(int $id,array $d,int $env,int $by):void{Database::transaction(function(PDO $db)use($id,$d,$env,$by){$s=$db->prepare('SELECT p.* FROM propietarios p JOIN propietarios_entornos pe ON pe.propietario_id=p.id WHERE p.id=:id AND pe.entorno_id=:e AND p.deleted_at IS NULL');$s->execute(['id'=>$id,'e'=>$env]);$old=$s->fetch();if(!$old)throw new RuntimeException('Propietario no encontrado.');$s=$db->prepare('UPDATE propietarios SET nombres=:n,apellidos=:a,email=:em,telefono=:t,celular=:c,direccion=:d WHERE id=:id');$s->execute(['n'=>trim((string)($d['nombres']??$old['nombres'])),'a'=>trim((string)($d['apellidos']??$old['apellidos']))?:null,'em'=>trim((string)($d['email']??$old['email']))?:null,'t'=>trim((string)($d['telefono']??$old['telefono']))?:null,'c'=>trim((string)($d['celular']??$old['celular']))?:null,'d'=>trim((string)($d['direccion']??$old['direccion']))?:null,'id'=>$id]);(new AuditService())->log($by,$env,'PROPIETARIOS','EDITAR','propietarios',$id,$old,$d);});}
 public function delete(int $id,int $env,int $by):void{$db=Database::connection();$s=$db->prepare('UPDATE propietarios p JOIN propietarios_entornos pe ON pe.propietario_id=p.id SET p.deleted_at=NOW(),p.activo=0,pe.activo=0 WHERE p.id=:id AND pe.entorno_id=:e');$s->execute(['id'=>$id,'e'=>$env]);(new AuditService())->log($by,$env,'PROPIETARIOS','ELIMINAR','propietarios',$id);}
}
