<?php
namespace App\Controllers\Auth;
use App\Core\Controller;use App\Core\Request;use App\Core\Session;use App\Core\Database;
class PasswordController extends Controller
{
 public function edit(Request $r):void{$this->view('auth/change-password',['error'=>Session::pullFlash('error')],'layouts/auth');}
 public function update(Request $r):void{if(!Session::validateCsrf($r->input('_token'))){http_response_code(419);return;}$p=(string)$r->input('password');$c=(string)$r->input('password_confirmation');if(strlen($p)<8||$p!==$c){Session::flash('error','La contraseña debe tener al menos 8 caracteres y coincidir.');$this->redirect('/cambiar-password');}$s=Database::connection()->prepare('UPDATE usuarios SET password_hash=:h,requiere_cambio_password=0,password_changed_at=NOW() WHERE id=:id');$s->execute(['h'=>password_hash($p,PASSWORD_DEFAULT),'id'=>auth_id()]);$u=auth_user();$u['requires_password_change']=false;Session::put('auth_user',$u);(new \App\Services\AuditService())->log(auth_id(),active_environment_id(),'AUTH','CAMBIO_PASSWORD','usuarios',auth_id());$this->redirect('/dashboard');}
 public function forgot(Request $r):void{$this->view('auth/forgot-password',['success'=>Session::pullFlash('success'),'error'=>Session::pullFlash('error')],'layouts/auth');}
 public function sendReset(Request $r):void{if(!Session::validateCsrf($r->input('_token'))){http_response_code(419);return;}$email=trim((string)$r->input('email'));$db=Database::connection();$s=$db->prepare('SELECT id FROM usuarios WHERE email=:e AND activo=1 AND deleted_at IS NULL');$s->execute(['e'=>$email]);$uid=$s->fetchColumn();if($uid){$token=bin2hex(random_bytes(32));$db->prepare('INSERT INTO password_reset_tokens(usuario_id,token_hash,expires_at) VALUES(:u,:t,DATE_ADD(NOW(),INTERVAL 60 MINUTE))')->execute(['u'=>$uid,'t'=>hash('sha256',$token)]);$link=url('/restablecer-password?token='.$token);$from=$_ENV['MAIL_FROM_ADDRESS']??'noreply@localhost';@mail($email,'Restablecer contraseña - Tu Huella Vet',"Usa este enlace durante los próximos 60 minutos:\n{$link}",'From: '.$from);if(($_ENV['APP_ENV']??'production')==='local')Session::flash('success','Enlace de desarrollo: '.$link);else Session::flash('success','Si el correo existe, se envió un enlace de recuperación.');}else Session::flash('success','Si el correo existe, se envió un enlace de recuperación.');$this->redirect('/olvide-password');}
 public function reset(Request $r):void{$token=(string)$r->input('token');$this->view('auth/reset-password',['token'=>$token,'error'=>Session::pullFlash('error')],'layouts/auth');}
 public function performReset(Request $r):void{if(!Session::validateCsrf($r->input('_token'))){http_response_code(419);return;}$token=(string)$r->input('token');$p=(string)$r->input('password');if(strlen($p)<8||$p!==(string)$r->input('password_confirmation')){Session::flash('error','Las contraseñas no coinciden o son demasiado cortas.');$this->redirect('/restablecer-password?token='.urlencode($token));}$db=Database::connection();$s=$db->prepare('SELECT * FROM password_reset_tokens WHERE token_hash=:t AND usado_at IS NULL AND expires_at>NOW() ORDER BY id DESC LIMIT 1');$s->execute(['t'=>hash('sha256',$token)]);$row=$s->fetch();if(!$row){Session::flash('error','El enlace es inválido o expiró.');$this->redirect('/restablecer-password?token='.urlencode($token));}Database::transaction(function($db)use($row,$p){$db->prepare('UPDATE usuarios SET password_hash=:h,requiere_cambio_password=0,password_changed_at=NOW() WHERE id=:u')->execute(['h'=>password_hash($p,PASSWORD_DEFAULT),'u'=>$row['usuario_id']]);$db->prepare('UPDATE password_reset_tokens SET usado_at=NOW() WHERE id=:id')->execute(['id'=>$row['id']]);});Session::flash('success','Contraseña actualizada. Ya puedes iniciar sesión.');$this->redirect('/login');}
}
