<?php

declare(strict_types=1);

return [
    'always_allowed_paths' => [
        '/dashboard',
        '/logout',
        '/empresa/seleccionar',
        '/empresa/cambiar',
        '/password/change',
        '/pdf/ver',
        '/pdf/descargar',
        '/imagen/ver',
    ],
    'blocked_by_role' => [
        'administrador' => [
            'roles.*',
            'permisos.*',
            'auditoria.*',
            'empresas.*',
            'configuracion.*',
        ],
        'cliente' => [
            'usuarios.*',
            'roles.*',
            'permisos.*',
            'auditoria.*',
            'empresas.*',
            'propietarios.*',
            'pacientes.*',
            'consultas.*',
            'vacunas.*',
            'desparasitaciones.*',
            'hospitalizaciones.*',
            'examenes.*',
            'cirugias.*',
            'formulas.*',
            'timeline.*',
            'inventario.*',
            'catalogos.*',
            'modulos.*',
        ],
        'invitado' => [
            'usuarios.*',
            'roles.*',
            'permisos.*',
            'auditoria.*',
            'empresas.*',
            'propietarios.*',
            'pacientes.*',
            'consultas.*',
            'vacunas.*',
            'desparasitaciones.*',
            'hospitalizaciones.*',
            'examenes.*',
            'cirugias.*',
            'formulas.*',
            'timeline.*',
            'inventario.*',
            'catalogos.*',
            'modulos.*',
        ],
    ],
    'default_role_permissions' => [
        'super_administrador' => ['*'],
        'administrador' => [
            'dashboard.ver',
            'propietarios.ver', 'propietarios.crear', 'propietarios.editar',
            'pacientes.ver', 'pacientes.crear', 'pacientes.editar',
            'consultas.ver', 'consultas.crear',
            'vacunas.ver', 'vacunas.crear', 'vacunas.editar', 'vacunas.eliminar',
            'desparasitaciones.ver', 'desparasitaciones.crear',
            'hospitalizaciones.ver', 'hospitalizaciones.crear', 'hospitalizaciones.editar',
            'cirugias.ver', 'cirugias.crear',
            'examenes.ver', 'examenes.crear',
            'formulas.ver', 'formulas.crear', 'formulas.editar', 'formulas.eliminar',
            'timeline.ver',
            'usuarios.ver', 'usuarios.crear', 'usuarios.editar',
            'catalogos.ver', 'catalogos.editar',
            'inventario.ver', 'inventario.editar',
        ],
        'cliente' => [
            'dashboard.ver',
            'cliente.panel.ver',
            'cliente.documentos.ver',
        ],
        'invitado' => [
            'dashboard.ver',
            'publico.ver',
        ],
    ],
    'route_map' => [
        'GET' => [
            '/dashboard' => 'dashboard.ver',
            '/propietarios' => 'propietarios.ver',
            '/propietarios/crear' => 'propietarios.crear',
            '/propietarios/editar' => 'propietarios.editar',
            '/animales' => 'pacientes.ver',
            '/animales/crear' => 'pacientes.crear',
            '/animales/editar' => 'pacientes.editar',
            '/consultas' => 'consultas.ver',
            '/consultas/crear' => 'consultas.crear',
            '/diagnosticos' => 'catalogos.ver',
            '/vacunas' => 'vacunas.ver',
            '/desparasitaciones' => 'desparasitaciones.ver',
            '/hospitalizaciones' => 'hospitalizaciones.ver',
            '/examenes' => 'examenes.ver',
            '/cirugias' => 'cirugias.ver',
            '/formulas' => 'formulas.ver',
            '/formulas/crear' => 'formulas.crear',
            '/formulas/editar' => 'formulas.editar',
            '/formulas/test' => 'formulas.ver',
            '/formulas/variables/detectar' => 'formulas.ver',
            '/timeline' => 'timeline.ver',
            '/auditoria' => 'auditoria.ver',
            '/usuarios' => 'usuarios.ver',
            '/roles' => 'roles.ver',
            '/permisos' => 'permisos.ver',
            '/especies' => 'catalogos.ver',
            '/razas' => 'catalogos.ver',
            '/categorias-animales' => 'catalogos.ver',
            '/empresas' => 'empresas.ver',
            '/medicamentos' => 'inventario.ver',
            '/laboratorios' => 'catalogos.ver',
            '/tipos-examen' => 'catalogos.ver',
        ],
        'POST' => [
            '/propietarios' => 'propietarios.crear',
            '/propietarios/actualizar' => 'propietarios.editar',
            '/animales' => 'pacientes.crear',
            '/animales/actualizar' => 'pacientes.editar',
            '/consultas' => 'consultas.crear',
            '/diagnosticos/catalogo' => 'catalogos.editar',
            '/diagnosticos/catalogo/actualizar' => 'catalogos.editar',
            '/diagnosticos/catalogo/eliminar' => 'catalogos.editar',
            '/diagnosticos/asignar' => 'consultas.editar',
            '/vacunas/catalogo' => 'vacunas.crear',
            '/vacunas/catalogo/actualizar' => 'vacunas.editar',
            '/vacunas/catalogo/eliminar' => 'vacunas.eliminar',
            '/vacunas/aplicar' => 'vacunas.editar',
            '/desparasitaciones' => 'desparasitaciones.crear',
            '/hospitalizaciones' => 'hospitalizaciones.crear',
            '/hospitalizaciones/tamanos' => 'hospitalizaciones.editar',
            '/hospitalizaciones/estado' => 'hospitalizaciones.editar',
            '/hospitalizaciones/fluidoterapia' => 'hospitalizaciones.editar',
            '/examenes' => 'examenes.crear',
            '/cirugias' => 'cirugias.crear',
            '/formulas' => 'formulas.crear',
            '/formulas/actualizar' => 'formulas.editar',
            '/formulas/eliminar' => 'formulas.eliminar',
            '/formulas/toggle' => 'formulas.editar',
            '/usuarios/crear' => 'usuarios.crear',
            '/usuarios/actualizar' => 'usuarios.editar',
            '/usuarios/estado' => 'usuarios.editar',
            '/usuarios/reset-password' => 'usuarios.editar',
            '/usuarios/asignaciones' => 'usuarios.editar',
            '/roles/crear' => 'roles.crear',
            '/roles/actualizar' => 'roles.editar',
            '/roles/duplicar' => 'roles.crear',
            '/roles/permisos' => 'roles.editar',
            '/permisos/crear' => 'permisos.crear',
            '/permisos/actualizar' => 'permisos.editar',
            '/permisos/sincronizar' => 'permisos.editar',
            '/especies/crear' => 'catalogos.editar',
            '/especies/actualizar' => 'catalogos.editar',
            '/especies/estado' => 'catalogos.editar',
            '/razas/crear' => 'catalogos.editar',
            '/razas/actualizar' => 'catalogos.editar',
            '/razas/estado' => 'catalogos.editar',
            '/categorias-animales/crear' => 'catalogos.editar',
            '/categorias-animales/actualizar' => 'catalogos.editar',
            '/categorias-animales/estado' => 'catalogos.editar',
            '/empresas/crear' => 'empresas.crear',
            '/empresas/actualizar' => 'empresas.editar',
            '/medicamentos/crear' => 'inventario.editar',
            '/medicamentos/actualizar' => 'inventario.editar',
            '/laboratorios/renombrar' => 'catalogos.editar',
            '/tipos-examen/renombrar' => 'catalogos.editar',
        ],
    ],
];
