<?php
namespace App\Controllers\Gestion;
use App\Core\Controller;use App\Core\Request;use App\Core\Database;
use Dompdf\Dompdf;use PhpOffice\PhpSpreadsheet\Spreadsheet;use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
class ReporteController extends Controller
{
    public function index(Request $r):void{$db=Database::connection();$e=active_environment_id();$stats=[];foreach(['Pacientes'=>'SELECT COUNT(*) FROM animales WHERE entorno_id=:e AND activo=1 AND deleted_at IS NULL','Consultas'=>'SELECT COUNT(*) FROM eventos_clinicos ec JOIN animales a ON a.id=ec.animal_id JOIN tipos_evento_clinico t ON t.id=ec.tipo_evento_id WHERE a.entorno_id=:e AND t.codigo="CONSULTA_EXTERNA"','Hospitalizaciones'=>'SELECT COUNT(*) FROM hospitalizaciones h JOIN eventos_clinicos ec ON ec.id=h.evento_clinico_id JOIN animales a ON a.id=ec.animal_id WHERE a.entorno_id=:e','Ventas'=>'SELECT COUNT(*) FROM ventas WHERE entorno_id=:e'] as $k=>$sql){$s=$db->prepare($sql);$s->execute(['e'=>$e]);$stats[$k]=(int)$s->fetchColumn();}$this->view('reportes/index',['title'=>'Reportes','stats'=>$stats]);}
    private function patients():array{$s=Database::connection()->prepare('SELECT a.id,a.codigo,a.nombre,e.nombre_comun AS especie,r.nombre AS raza,s.nombre AS sexo,(SELECT peso_kg FROM animales_pesos WHERE animal_id=a.id ORDER BY fecha_registro DESC,id DESC LIMIT 1) AS peso FROM animales a JOIN especies e ON e.id=a.especie_id LEFT JOIN razas r ON r.id=a.raza_id LEFT JOIN sexos_animales s ON s.id=a.sexo_id WHERE a.entorno_id=:e AND a.deleted_at IS NULL ORDER BY a.nombre');$s->execute(['e'=>active_environment_id()]);return$s->fetchAll();}
    public function csv(Request $r):void{header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="pacientes.csv"');$o=fopen('php://output','w');fputcsv($o,['ID','Código','Nombre','Especie','Raza','Sexo','Peso']);foreach($this->patients() as $x)fputcsv($o,$x);fclose($o);exit;}
    public function xlsx(Request $r):void{$ss=new Spreadsheet();$sh=$ss->getActiveSheet();$sh->fromArray(['ID','Código','Nombre','Especie','Raza','Sexo','Peso'],null,'A1');$row=2;foreach($this->patients() as $x){$sh->fromArray(array_values($x),null,'A'.$row++);}foreach(range('A','G') as $c)$sh->getColumnDimension($c)->setAutoSize(true);header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="pacientes.xlsx"');(new Xlsx($ss))->save('php://output');exit;}
    public function pdf(Request $r):void{$rows=$this->patients();$html='<h1>Reporte de pacientes</h1><table width="100%" border="1" cellspacing="0" cellpadding="5"><tr><th>Nombre</th><th>Especie</th><th>Raza</th><th>Peso</th></tr>';foreach($rows as $x)$html.='<tr><td>'.htmlspecialchars((string)$x['nombre']).'</td><td>'.htmlspecialchars((string)$x['especie']).'</td><td>'.htmlspecialchars((string)($x['raza']??'')).'</td><td>'.htmlspecialchars((string)($x['peso']??'')).'</td></tr>';$html.='</table>';$d=new Dompdf();$d->loadHtml($html,'UTF-8');$d->setPaper('A4','portrait');$d->render();$d->stream('pacientes.pdf',['Attachment'=>true]);exit;}
}
