<?php
namespace App\Models;use App\Core\Model;
class Hospitalization extends Model
{
 public function list(int $e,string $q=''):array{$sql='SELECT h.*,ec.animal_id,a.nombre AS paciente,es.nombre_comun AS especie,r.nombre AS raza,eh.codigo AS estado_codigo,eh.nombre AS estado_nombre,p.nombres AS propietario_nombres,p.apellidos AS propietario_apellidos FROM hospitalizaciones h JOIN eventos_clinicos ec ON ec.id=h.evento_clinico_id JOIN animales a ON a.id=ec.animal_id JOIN especies es ON es.id=a.especie_id LEFT JOIN razas r ON r.id=a.raza_id LEFT JOIN propietarios_entornos pe ON pe.id=a.propietario_entorno_id LEFT JOIN propietarios p ON p.id=pe.propietario_id JOIN estados_hospitalizacion eh ON eh.id=h.estado_hospitalizacion_id WHERE a.entorno_id=:e AND a.deleted_at IS NULL';$p=['e'=>$e];if($q!==''){$sql.=' AND CONCAT_WS(" ",a.nombre,es.nombre_comun,r.nombre,p.nombres,p.apellidos,h.motivo_ingreso) LIKE :q';$p['q']='%'.$q.'%';}$s=$this->db->prepare($sql.' ORDER BY h.fecha_ingreso DESC');$s->execute($p);return$s->fetchAll();}
 public function find(int $id,int $e):?array{$s=$this->db->prepare('SELECT h.*,ec.animal_id,ec.responsable_id,a.nombre AS paciente,a.especie_id,es.nombre_comun AS especie,r.nombre AS raza,sx.nombre AS sexo,eh.codigo AS estado_codigo,eh.nombre AS estado_nombre,CONCAT(u.nombres," ",u.apellidos) AS responsable_ingreso_nombre,CONCAT(ua.nombres," ",ua.apellidos) AS responsable_alta_nombre,(SELECT peso_kg FROM animales_pesos WHERE animal_id=a.id ORDER BY fecha_registro DESC,id DESC LIMIT 1) AS peso_actual FROM hospitalizaciones h JOIN eventos_clinicos ec ON ec.id=h.evento_clinico_id JOIN animales a ON a.id=ec.animal_id JOIN especies es ON es.id=a.especie_id LEFT JOIN razas r ON r.id=a.raza_id LEFT JOIN sexos_animales sx ON sx.id=a.sexo_id JOIN estados_hospitalizacion eh ON eh.id=h.estado_hospitalizacion_id JOIN usuarios u ON u.id=ec.responsable_id LEFT JOIN usuarios ua ON ua.id=h.responsable_alta_id WHERE h.evento_clinico_id=:id AND a.entorno_id=:e LIMIT 1');$s->execute(['id'=>$id,'e'=>$e]);return$s->fetch()?:null;}
 private function rows(string $sql,int $id):array{$s=$this->db->prepare($sql);$s->execute(['id'=>$id]);return$s->fetchAll();}
 public function signs(int $id):array{return$this->rows('SELECT hs.*,CONCAT(u.nombres," ",u.apellidos) AS registrado_por_nombre FROM hospitalizacion_signos hs JOIN usuarios u ON u.id=hs.registrado_por WHERE hs.hospitalizacion_evento_id=:id ORDER BY hs.fecha_hora DESC',$id);}
 public function evolutions(int $id):array{return$this->rows('SELECT he.*,CONCAT(u.nombres," ",u.apellidos) AS registrado_por_nombre FROM hospitalizacion_evoluciones he JOIN usuarios u ON u.id=he.registrado_por WHERE he.hospitalizacion_evento_id=:id ORDER BY he.fecha_hora DESC',$id);}
 public function fluids(int $id):array{return$this->rows('SELECT hf.*,cm.nombre AS categoria_nombre,f.nombre AS formula_nombre,fe.resultado AS formula_resultado,um.simbolo AS formula_unidad FROM hospitalizacion_fluidoterapias hf LEFT JOIN categorias_mantenimiento_fluido cm ON cm.id=hf.categoria_mantenimiento_id LEFT JOIN formulas f ON f.id=hf.formula_id LEFT JOIN formula_ejecuciones fe ON fe.id=hf.formula_ejecucion_id LEFT JOIN unidades_medida um ON um.id=fe.unidad_resultado_id WHERE hf.hospitalizacion_evento_id=:id ORDER BY hf.fecha_inicio DESC',$id);}
 public function statuses():array{return$this->db->query('SELECT id,codigo,nombre FROM estados_hospitalizacion WHERE activo=1 ORDER BY id')->fetchAll();}
 public function maintenance(?int $species=null):array{$sql='SELECT * FROM categorias_mantenimiento_fluido WHERE activo=1';$p=[];if($species){$sql.=' AND (especie_id IS NULL OR especie_id=:e)';$p['e']=$species;}$s=$this->db->prepare($sql.' ORDER BY nombre');$s->execute($p);return$s->fetchAll();}
}
